name: pomodoro
description: A Desktop Pomodoro Timer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  bloc: ^7.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.9.2
  desktop_window: ^0.4.0
  equatable: ^2.0.2
  flushbar: ^1.10.4
  flutter_bloc: ^7.0.1
  flutter_local_notifications: ^6.0.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  injectable: ^1.4.1
  just_audio: ^0.7.5
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  window_activator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.0.4
  injectable_generator: ^1.4.1
  very_good_analysis: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - audio/ding.mp3
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
