name: pomodoro
description: A Desktop Pomodoro Timer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  bitsdojo_window: ^0.1.1+1
  bloc: ^7.1.0
  context_menus: ^0.1.0+5
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  desktop_window: ^0.4.0
  equatable: ^2.0.3
  flushbar: ^1.10.4
  flutter_bloc: ^7.2.0
  flutter_local_notifications: ^8.1.1+2
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  injectable: ^1.5.0
  just_audio: ^0.9.10
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  window_activator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.2
  injectable_generator: ^1.5.2
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - audio/ding.mp3
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
